apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend-namespace
data:
  krakend.json: |
    {
      "version": 2,
      "name": "Krakend Example",
      "extra_config": {},
      "endpoints": [
        {
          "endpoint": "/hello",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/",
              "host": [
                "http://example.com"
              ]
            }
          ]
        }
      ]
    }