---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MGWT2",
             "port" : 9098,
             "host" : [ "localhost" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/jmespath",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io/" ],
                 "url_pattern" : "/",
                 "extra_config" : {
                   "modifier/jmespath" : {
                     "expr" : "country[?probability > `0.0` ].country_id"
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/merge",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/1",
                 "is_collection" : false,
                 "method" : "GET"
               }, {
                 "host" : [ "https://api.nationalize.io/" ],
                 "url_pattern" : "/",
                 "allow" : [ "" ],
                 "mapping" : { },
                 "group" : "",
                 "is_collection" : false,
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "deny" : [ "" ],
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             }, {
               "endpoint" : "/SK1",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "encoding" : "json",
                 "extra_config" : {
                   "modifier/body-generator" : {
                     "template" : "{\n                  \"type\": \"object\",\n                  \"required\": [\"number\", \"street_name\", \"street_type\"],\n                  \"properties\": {\n                    \"number\":      { \"type\": \"number\" },\n                    \"street_name\": { \"type\": \"string\" },\n                    \"street_type\": { \"type\": \"string\"   }\n                  }\n                }",
                     "content_type" : "application/json"
                   }
                 },
                 "method" : "POST",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "POST"
             }, {
               "endpoint" : "/SK2",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev" ],
                 "url_pattern" : "/objects",
                 "mapping" : { },
                 "is_collection" : true,
                 "encoding" : "json",
                 "extra_config" : {
                   "qos/ratelimit/proxy" : {
                     "max_rate" : 3,
                     "capacity" : 3,
                     "every" : "1m"
                   },
                   "modifier/response-body-generator" : {
                     "template" : "{\n  \"data\": {{ toJson .resp_body }},\n  \"status_code\": {{ toJson .resp_status }},\n  \"headers\": {{ toJson .resp_headers }},\n}\n"
                   },
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "collection.*.data", "collection.*.newdata" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/testpathparamvald/{id}",
               "backend" : [ {
                 "host" : [ "https://jsonplaceholder.typicode.com" ],
                 "url_pattern" : "/posts/{id}",
                 "mapping" : { },
                 "is_collection" : false,
                 "extra_config" : {
                   "proxy" : { },
                   "security/policies" : {
                     "req" : {
                       "policies" : [ "req_params.id.matches('^[0-9]+$')" ],
                       "error" : {
                         "body" : "id must be Integer",
                         "status" : 400,
                         "content_type" : "application/json"
                       }
                     },
                     "jwt" : {
                       "policies" : [ "" ]
                     },
                     "resp" : {
                       "policies" : [ "" ]
                     }
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/flatmap",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "mapping" : { },
                 "is_collection" : false,
                 "extra_config" : {
                   "proxy" : {
                     "flatmap_filter" : [ {
                       "type" : "move",
                       "args" : [ "data.year", "year" ]
                     } ]
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/target",
               "backend" : [ {
                 "host" : [ "https://api.restful-api.dev/" ],
                 "url_pattern" : "/objects/7",
                 "mapping" : { },
                 "is_collection" : false,
                 "extra_config" : {
                   "proxy" : { }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET"
             }, {
               "endpoint" : "/requestschemavalidation",
               "backend" : [ {
                 "host" : [ "https://localhost:8090" ],
                 "url_pattern" : "/__health",
                 "extra_config" : {
                   "modifier/body-generator" : {
                     "template" : "{\n                  \"type\": \"object\",\n                  \"required\": [\"number\", \"street_name\", \"street_type\"],\n                  \"properties\": {\n                    \"number\":      { \"type\": \"number\" },\n                    \"street_name\": { \"type\": \"string\" },\n                    \"street_type\": { \"type\": \"string\"   }\n                  }\n                }"
                   }
                 },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "POST"
             } ],
             "extra_config" : { }
           }
