apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend-namespace
data:
  krakend.json: |
    {
        "$schema": "https://www.krakend.io/schema/krakend.json",
        "version": 3,
        "name": "APIGateway",
        "timeout": "3000ms",
        "cache_ttl": "300s",
        "port": 8080,
        "endpoints": [
            {
                "endpoint": "/api/posts",
                "method": "GET",
                "output_encoding": "json",
                "backend": [
                    {
                        "url_pattern": "/posts/1",
                        "host": [
                            "https://jsonplaceholder.typicode.com/"
                        ]
                    }
                ]
            }
        ]
    }
