apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend-namespace
data:
  krakend.json: |
           {
             "$schema" : "https://www.krakend.io/schema/krakend.json",
             "version" : 3,
             "name" : "MassilGW",
             "port" : 8080,
             "host" : [ "localhost" ],
             "timeout" : "3000ms",
             "cache_ttl" : "300s",
             "debug_endpoint" : false,
             "echo_endpoint" : false,
             "endpoints" : [ {
               "endpoint" : "/jmespath",
               "backend" : [ {
                 "host" : [ "https://api.nationalize.io/" ],
                 "url_pattern" : "/",
                 "extra_config" : { },
                 "method" : "GET",
                 "disable_host_sanitize" : true
               } ],
               "extra_config" : { },
               "method" : "GET",
               "input_query_strings" : [ "name" ]
             } ],
             "extra_config" : { }
           }
