apiVersion: v1
kind: Service
metadata:
  name: krakend-service
  namespace: krakend-namespace
spec:
  selector:
    app: krakend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    NodePort: 31321
  type: NodePort
