apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: {{ .Values.namespace }}
data:
  krakend.json: |
    {
      "$schema": "https://www.krakend.io/schema/krakend.json",
      "version": 3,
      "name": "APIGateway",
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "output_encoding": "no-op",
      "port": 8080,
      "endpoints": [
        {
          "endpoint": "/api/posts",
          "method": "GET",
          "output_encoding": "json",
          "backend": [
            {
              "url_pattern": "/posts/1",
              "host": [
                "https://jsonplaceholder.typicode.com"
              ]
            }
          ]
        },
        {
          "endpoint": "/SK1",
          "method": "POST",
          "backend": [
            {
              "host": [
                "https://api.restful-api.dev"
              ],
              "url_pattern": "/objects/7",
              "disable_host_sanitize": true
            }
          ]
        }
      ]
    }