apiVersion: v1
kind: Service
metadata:
  name: krakend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: krakend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}